# Generated by Django 4.0.4 on 2022-05-02 21:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_alter_gymclassattendance_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='gymclass',
            name='capacity',
            field=models.IntegerField(default=20),
        ),
        migrations.AlterField(
            model_name='gymclassattendance',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.gymclass'),
        ),
        migrations.AlterField(
            model_name='gymclassattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gym.member'),
        ),
    ]
