# Generated by Django 4.0.3 on 2022-04-21 06:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_employee_equipment_member_membership_servicehistory_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClassAttendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RenameModel(
            old_name='Session',
            new_name='GymClass',
        ),
        migrations.DeleteModel(
            name='SessionAttendance',
        ),
        migrations.AddField(
            model_name='gymclassattendance',
            name='gym_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.gymclass'),
        ),
        migrations.AddField(
            model_name='gymclassattendance',
            name='member',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='gym.employee'),
        ),
    ]
