# Generated by Django 4.0.4 on 2022-05-02 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_gymclass_capacity_alter_gymclassattendance_gym_class_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gymclassattendance',
            unique_together={('gym_class', 'member')},
        ),
    ]
